# Generated by Django 3.1.3 on 2020-12-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favproduct',
            old_name='item',
            new_name='items',
        ),
    ]
