# Generated by Django 3.1.3 on 2020-12-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_auto_20201211_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favproduct',
            old_name='items',
            new_name='item',
        ),
    ]
