# Generated by Django 3.1.3 on 2020-12-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_favoriteproduct'),
        ('favorites', '0003_auto_20201211_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favproduct',
            name='item',
        ),
        migrations.AddField(
            model_name='favproduct',
            name='item',
            field=models.ManyToManyField(related_name='fav_item', to='products.Product'),
        ),
    ]
