# Generated by Django 3.1.3 on 2020-12-24 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_favoriteproduct'),
        ('favorites', '0004_auto_20201224_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favproduct',
            name='item',
        ),
        migrations.AddField(
            model_name='favproduct',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_item', to='products.product'),
        ),
    ]
