# Generated by Django 3.1.3 on 2020-11-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20201130_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
