# Generated by Django 3.1.3 on 2020-12-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20201201_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
