# Generated by Django 3.1.3 on 2020-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20201201_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='delete',
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
