# Generated by Django 3.1.3 on 2020-12-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20201217_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(blank=True, related_name='cart_item', to='cart.CartItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
