# Generated by Django 3.1.3 on 2020-12-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_favoriteproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
